name: Build

on:
  workflow_call:
    inputs:
      artifact-name:
        description: Name of the downloadable workflow artifact
        required: true
        type: string
      retention-days:
        description: Number of days to retain the temporary workflow artifact
        required: false
        default: 7
        type: number

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: gd
          tools: composer

      - name: Build release zip
        run: bin/build-release-zip

      - name: Upload package artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.artifact-name }}
          path: dist/myparcel.ocmod.zip
          retention-days: ${{ inputs.retention-days }}
          if-no-files-found: error
