name: Custom build

on:
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: custom-build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      artifact-name: myparcel-ocmod-custom-${{ github.sha }}
      retention-days: 14
